name: build

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod  # Ensures the Go version specified in go.mod is used

      - name: Install Linter
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run lint
        run: make lint

      - name: Format code
        run: make fmt

      - name: Run Tests
        run: make test
   
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          distribution: goreleaser
          version: 2
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
